#!/bin/sh
### BEGIN INIT INFO
# Provides:          Für welches Programm ist das Script?
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Kurze Beschreibung
# Description:       Längere Beschreibung
### END INIT INFO
 
# Actions
case "$1" in
    start)
        # START
	echo "Start Disp-Software"
	cd /programs/office_display
	sudo python officedisplay.py &
        ;;
    stop)
        # STOP
	echo "Stop Disp-Software"
	sudo killall python officedisplay.py
        ;;
    restart)
        # RESTART
	echo "Restart Disp-Software"
	sudo killall python officedisplay.py
	cd /programs/office_display
	sudo python officedisplay.py &

        ;;
esac
 
exit 0


